### ISSUE TITLE
Error running the example upon SIP connect

### ISSUE THREAD

**Issue by jasonlaw** [iampato/sip_native#2]
D/SIP Native(10236): Sip manager cannot be null
W/System.err(10236): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.net.sip.SipManager.open(android.net.sip.SipProfile, android.app.PendingIntent, android.net.sip.SipRegistrationListener)' on a null object reference
W/System.err(10236): 	at me.iampato.sip_native.SipDataManager.initializeProfile(SipDataManager.java:108)
W/System.err(10236): 	at me.iampato.sip_native.SipNativePlugin.onMethodCall(SipNativePlugin.java:121)
W/System.err(10236): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(10236): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(10236): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/System.err(10236): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(10236): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(10236): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(10236): 	at android.os.Looper.loop(Looper.java:223)
W/System.err(10236): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err(10236): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(10236): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err(10236): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter (10236): Sip connect response: false

**Comment by iampato** [comment]
Could you send me a snippet so that I can try replicating it on my end

**Comment by jasonlaw** [comment]
Thanks for looking into this. I am running the example in the package, with the SIP connection info changed only.

You may take a look in my forked out branch.
https://github.com/jasonlaw/sip_native

Here is my flutter environment:
~~~
PS D:\JSL\GitHub\flutter\sip_native> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.1)
[√] VS Code, 64-bit edition (version 1.70.2)
[√] Connected device (2 available)
[√] HTTP Host Availability
~~~

**Comment by iampato** [comment]
Are you using a physical device or an emulator?

**Comment by jasonlaw** [comment]
I am using an emulator

**Comment by iampato** [comment]
@jasonlaw  that's why try it on a physical device (please read the READMe file)
