### ISSUE TITLE
Error when init call

### ISSUE THREAD

**Issue by jasonlaw** [iampato/sip_native#3]
Hi @iampato ,

I tried with a physical phone and the SIP connect is success now.
However, when I tried to init the call, I got the FormatException
![image](https://user-images.githubusercontent.com/107820/186833224-d70490bb-a6cd-4cab-b281-2a19c7793200.png)

FYI, I am trying to initial call at sip:yllew@sip.linphone.org.

Thanks in advance.

**Comment by iampato** [comment]
Hey @jasonlaw I see the format is wrong: `sip:..` not accepted
Just enter the username alone
